# Generated by Django 5.0.7 on 2024-07-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_anexo_delete_task'),
        ('user', '0002_user_area_user_condition_user_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexo', to='personal.anexo'),
        ),
    ]
