# Generated by Django 5.0.7 on 2024-08-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='img/empty.png', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
