# Generated by Django 5.0.7 on 2024-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
    ]
