# Generated by Django 5.0.7 on 2024-09-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grupo',
        ),
    ]
