# Generated by Django 5.0.7 on 2024-09-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0008_remove_user_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo_users', to='auth.group'),
        ),
    ]
