# Generated by Django 5.0.7 on 2024-09-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grupo',
        ),
    ]
