# Generated by Django 5.0.13 on 2025-04-04 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_cargo_profesion'),
        ('user', '0011_user_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_users', to='personal.cargo'),
        ),
    ]
