# Generated by Django 5.0.13 on 2025-04-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_alter_cargo_name'),
        ('user', '0012_user_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_cesado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cese'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='user',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_users', to='personal.profesion'),
        ),
        migrations.AddField(
            model_name='user',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Sueldo'),
            preserve_default=False,
        ),
    ]
