# Generated by Django 5.0.13 on 2025-04-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_grupoocupacional'),
        ('user', '0014_user_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grupoOcupacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupOcu_users', to='personal.grupoocupacional'),
        ),
    ]
