# Generated by Django 5.0.13 on 2025-04-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_estado'),
        ('user', '0015_user_grupoocupacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo_estado', to='personal.estado'),
        ),
    ]
