# Generated by Django 5.0.13 on 2025-04-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_generica_alter_estado_descripcion'),
        ('user', '0016_user_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupo_generica', to='personal.generica'),
        ),
    ]
