# Generated by Django 5.0.14 on 2025-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_generica'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceso_poi',
            field=models.BooleanField(default=False, verbose_name='Acceso al POI'),
        ),
    ]
