# Generated by Django 5.0.14 on 2025-07-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_acceso_poi'),
    ]

    operations = [
    ]
