# Generated by Django 5.0.14 on 2025-07-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20250704_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceso_administracion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
