# Generated by Django 5.0.14 on 2025-07-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_acceso_administracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo'),
        ),
    ]
