# Generated by Django 5.0.13 on 2025-04-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario asignado')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación física')),
                ('codigo_2024', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código 2024')),
                ('codigo_ant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código anterior')),
                ('codigo_sbn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código SBN')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código interno')),
                ('denominacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Denominación')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle adicional')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensiones')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor actual')),
                ('estado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Equipo de patrimonio informático',
                'verbose_name_plural': 'Equipos de patrimonio informático',
                'db_table': 'patrimonio_informatico',
                'ordering': ['codigo_2024', 'denominacion'],
            },
        ),
    ]
