# Generated by Django 5.0.7 on 2024-07-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='get_dependencia', to='personal.area', verbose_name='Dependencia'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dependencia',
            unique_together={('name', 'area')},
        ),
        migrations.RemoveField(
            model_name='area',
            name='dependencia',
        ),
    ]
