# Generated by Django 5.0.7 on 2024-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
