# Generated by Django 5.0.7 on 2024-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_anexo_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='name',
            field=models.IntegerField(max_length=255, unique=True),
        ),
    ]
