# Generated by Django 5.0.7 on 2024-07-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_anexo_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexo',
            options={'ordering': ['number'], 'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='name',
        ),
        migrations.AddField(
            model_name='anexo',
            name='number',
            field=models.IntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
