# Generated by Django 5.0.7 on 2024-07-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_anexo_number_alter_area_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
