# Generated by Django 5.0.7 on 2024-07-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_alter_dependencia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_area', to='personal.area', verbose_name='Area'),
        ),
    ]
