# Generated by Django 5.0.7 on 2024-07-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_alter_dependencia_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependencia',
            unique_together=set(),
        ),
    ]
