# Generated by Django 5.0.7 on 2024-07-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_dependencia_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='area',
        ),
    ]
