# Generated by Django 5.0.7 on 2024-07-28 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_remove_dependencia_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='dependencia',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='personal.dependencia'),
            preserve_default=False,
        ),
    ]
