# Generated by Django 5.0.7 on 2024-07-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_area_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
