# Generated by Django 5.0.7 on 2024-07-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_alter_area_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='dependencia',
        ),
        migrations.CreateModel(
            name='DependenciaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_dependencias', to='personal.area')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia_areas', to='personal.dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia-Area',
                'verbose_name_plural': 'Dependencias-Areas',
                'unique_together': {('dependencia', 'area')},
            },
        ),
    ]
