# Generated by Django 5.0.13 on 2025-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_alter_cargo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Grupo Ocupacional')),
            ],
            options={
                'verbose_name': 'GrupoOcupacional',
                'verbose_name_plural': 'GrupoOcupacionales',
                'ordering': ['descripcion'],
            },
        ),
    ]
