# Generated by Django 5.0.13 on 2025-04-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('detalle', models.CharField(max_length=255, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Generica',
                'verbose_name_plural': 'Genericas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripcion'),
        ),
    ]
