# Generated by Django 5.0.7 on 2024-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, verbose_name='Código')),
                ('institucion', models.CharField(max_length=150, verbose_name='Institución')),
                ('departamento', models.CharField(max_length=150, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=150, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=150, verbose_name='Distrito')),
                ('disa', models.CharField(max_length=150, verbose_name='Disa')),
                ('categoria', models.CharField(max_length=150, verbose_name='Categoría')),
                ('establecimiento', models.CharField(max_length=300, verbose_name='Establecimiento')),
            ],
        ),
    ]
