# Generated by Django 5.0.13 on 2025-04-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informatica',
            name='ape_res',
        ),
        migrations.RemoveField(
            model_name='informatica',
            name='nom_res',
        ),
    ]
