# Generated by Django 5.0.13 on 2025-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0002_remove_informatica_ape_res_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informatica',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='condicion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='condicion1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condición Responsable'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='dependencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='dependencia1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dependencia Responsable'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='user_res',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Responsable'),
        ),
        migrations.AlterField(
            model_name='informatica',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
