# Generated by Django 5.0.13 on 2025-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0003_alter_informatica_area_alter_informatica_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatica',
            name='antiguedad',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Antiguedad'),
        ),
    ]
