# Generated by Django 5.0.13 on 2025-04-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0004_informatica_antiguedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informatica',
            name='estado',
        ),
    ]
