# Generated by Django 5.0.13 on 2025-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0005_remove_informatica_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatica',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
