# Generated by Django 5.0.13 on 2025-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0006_informatica_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='informatica',
            name='con_equipo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condición Equipo'),
        ),
    ]
