# Generated by Django 5.0.14 on 2025-05-23 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0020_generica_alter_estado_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedidaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, verbose_name='Código')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='MedidaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.CharField(max_length=20, verbose_name='Mes')),
                ('prog_fisica', models.IntegerField(blank=True, default=0, null=True, verbose_name='Prog. Física')),
                ('repro_fisica', models.IntegerField(blank=True, default=0, null=True, verbose_name='Repro. Física')),
                ('ejec_fisica', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ejec. Física')),
                ('comentario', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sustento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sustento')),
                ('campos_bloqueados', models.BooleanField(default=False, verbose_name='Campos Bloqueados')),
                ('dias_adicionales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.dependencia', verbose_name='Centro de costo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poi.grupo', verbose_name='Grupo')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.medidaactividad', verbose_name='Medida')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.CharField(max_length=20, verbose_name='Mes')),
                ('prog_ppto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prog. Presupuestal')),
                ('prog_5_21', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prog. Gen. 5.21')),
                ('prog_5_23', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prog. Gen. 5.23')),
                ('prog_5_26', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prog. Gen. 5.26')),
                ('repro_ppto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Act. Presupuestal')),
                ('act_5_21', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Act. Gen. 5.21')),
                ('act_5_23', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Act. Gen. 5.23')),
                ('act_5_26', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Act. Gen. 5.26')),
                ('ejec_ppto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ejec. Presupuestal')),
                ('ejec_5_21', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ejec. Gen. 5.21')),
                ('ejec_5_23', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ejec. Gen. 5.23')),
                ('ejec_5_26', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ejec. Gen. 5.26')),
                ('campos_bloqueados', models.BooleanField(default=False, verbose_name='Campos Bloqueados')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_actividad', to='poi.actividad', verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reporte_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='poi.reportetarea')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('trazabilidad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='Trazabilidad')),
                ('criterio', models.TextField(blank=True, null=True, verbose_name='Criterio')),
                ('definicion', models.TextField(blank=True, null=True, verbose_name='Definicion')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.actividad', verbose_name='Actividad')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.medidatarea', verbose_name='Medida')),
            ],
        ),
        migrations.AddField(
            model_name='reportetarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_tarea', to='poi.tarea', verbose_name='Tarea'),
        ),
    ]
