# Generated by Django 5.0.14 on 2025-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportetarea',
            name='alerta',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alerta'),
        ),
        migrations.AddField(
            model_name='reportetarea',
            name='recomendaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Recomendaciones'),
        ),
    ]
