# Generated by Django 5.0.14 on 2025-06-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0002_reportetarea_alerta_reportetarea_recomendaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportetarea',
            name='alerta',
            field=models.TextField(blank=True, null=True, verbose_name='Alerta'),
        ),
        migrations.AlterField(
            model_name='reportetarea',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='reportetarea',
            name='sustento',
            field=models.TextField(blank=True, null=True, verbose_name='Sustento'),
        ),
    ]
