# Generated by Django 5.0.14 on 2025-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_alter_reportetarea_alerta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportetarea',
            name='sustento',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
