# Generated by Django 5.0.14 on 2025-06-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0004_alter_reportetarea_sustento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='reportetarea',
            name='sustento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
