# Generated by Django 5.0.14 on 2025-06-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0005_remove_actividad_grupo_alter_reportetarea_sustento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteactividad',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendaciones'),
        ),
    ]
